---
driver:
  name: ec2
  region: us-east-1
  availability_zone: us-east-1b

provisioner:
  name: dummy

platforms:
  - name: packer_AWS
    driver:
      image_id: ami-079c3b1b38309f925
    transport:
      username: ubuntu
      ssh_key: home/nikolay/AWS_key/aws_key_pair.pem
    
verifier:
  name: inspec

suites:
  - name: default
