---
driver:
  name: ec2
  aws_ssh_key_id: packer_AWS
  region: us-east-2

provisioner:
  name: dummy

platforms:
  - name: packer_AWS
    driver:
      image_id: ami-02cf39d4fa8e9c764
    transport:
      username: ubuntu
      ssh_key: home/nikolay/AWS_key/aws_key_pair.pem
    
verifier:
  name: inspec

suites:
  - name: default
