---
driver:
  name: ec2
  aws_ssh_key_id: aws_key_pair
  region: us-east-2

provisioner:
  name: dummy

platforms:
  - name: packer_AWS
    driver:
      image_id: ami-05140b6843d91e894
    transport:
      username: ubuntu
      ssh_key: home/nikolay/AWS_key/aws_key_pair.pem
    
verifier:
  name: inspec

suites:
  - name: default
