---
driver:
  name: ec2
  aws_ssh_key_id: aws_key_pair
  region: us-east-1

provisioner:
  name: dummy

platforms:
  - name: packer_AWS
    driver:
      image_id: ami-04b8c2001b0bf0c27
    transport:
      username: ubuntu
      ssh_key: home/nikolay/AWS_key/aws_key_pair.pem
    
verifier:
  name: inspec

suites:
  - name: default
